routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', 'HomeController@index');

Auth::routes();

Route::group(['middleware' => ['auth']], function () {

	/*  TOOLS */

	// Tools home
    Route::get('/tools', 'MarketToolsController@home')->name('tools.home');
	// Reset market day - must be above /tools/{market_day} since that matches /tools/reset
	Route::get('/tools/reset', 'MarketToolsController@resetMarketDay')->name('tools.reset');
	// maanges a particular market day
    Route::get('/tools/dashboard/{market_day}', 'MarketToolsController@dashboard')->name('tools.dashboard');



    // Distribute Scrips
    Route::get('/tools/{market_day}/distribute_scrip', 'DistributeScripController@index')->name('tools.distribute_scrip.index');
    Route::get('/tools/{market_day}/distribute_scrip/create', 'DistributeScripController@create')->name('tools.distribute_scrip.create');
    Route::post('/tools/{market_day}/distribute_scrip', 'DistributeScripController@storeOrUpdate')->name('tools.distribute_scrip.store');
    Route::get('/tools/{market_day}/distribute_scrip/{scrip_sale}/', 'DistributeScripController@edit')->name('tools.distribute_scrip.edit');
    Route::patch('/tools/{market_day}/distribute_scrip/{scrip_sale}/', 'DistributeScripController@storeOrUpdate')->name('tools.distribute_scrip.update');
	Route::delete('/tools/{market_day}/distribute_scrip/{scrip_sale}', 'DistributeScripController@removeScripSaleFromMarketDay')->name('tools.distribute_scrip.destroy');



	// BOOTH FEES
    Route::get('/tools/{market_day}/booth_fees', 'MarketToolsController@showBoothFees')->name('tools.show_booth_fees');
    Route::get('/tools/{market_day}/booth_fees/{vendor}', 'MarketToolsController@showBoothFeesForVendor')->name('tools.show_booth_fees_for_vendor');
    Route::patch('/tools/{market_day}/booth_fees/{vendor}', 'MarketToolsController@updateBoothFeesForVendor')->name('tools.update_booth_fees_for_vendor');



    // Collect Scrips
    Route::get('/tools/{market_day}/collect_scrips', 'MarketToolsController@showCollectScrips')->name('tools.show_collect_scrips');
    Route::get('/tools/{market_day}/collect_scrips/{vendor}', 'MarketToolsController@showCollectScripsForVendor')->name('tools.show_collect_scrips_for_vendor');
    Route::patch('/tools/{market_day}/collect_scrips/{vendor}', 'MarketToolsController@updateCollectScripsForVendor')->name('tools.update_collect_scrips_for_vendor');
    Route::post('/tools/{market_day}/collect_scrips/{vendor}', 'MarketToolsController@addScripToVendor')->name('tools.add_scrip_to_vendor');
    Route::delete('/tools/{market_day}/collect_scrips/{vendor}/{scrip}', 'MarketToolsController@removeScripFromVendor')->name('tools.remove_scrip_from_vendor');
//	Route::get('/reports/collect_scrips', 'ReportController@collectScrips')->name('reports.collect_scrips');


	// ESTIMATED SALES
	Route::get('/tools/{market_day}/estimated_sales', 'MarketToolsController@showEstimatedSales')->name('tools.show_estimated_sales');
    Route::get('/tools/{market_day}/estimated_sales/{vendor}', 'MarketToolsController@showEstimatedSalesForVendor')->name('tools.show_estimated_sales_for_vendor');
    Route::patch('/tools/{market_day}/estimated_sales/{vendor}', 'MarketToolsController@updateEstimatedSalesForVendor')->name('tools.update_estimated_sales_for_vendor');

//	Route::get('/reports/estimated_sales', 'ReportController@estimatedSales')->name('reports.estimated_sales');

	// REPORTS
    Route::get('/reports', 'ReportController@home')->name('reports.index');
//    Route::get('/reports/booth_fees/{market_day}', 'ReportController@boothFees')->name('reports.booth_fees');
    Route::get('/reports/booth_fees_form', 'ReportController@boothFeesForm')->name('reports.booth_fees_form');
    Route::get('/reports/booth_fees/{market_day}', 'ReportController@boothFees')->name('reports.booth_fees');
    Route::get('/reports/estimated_sales_form', 'ReportController@estimatedSalesForm')->name('reports.estimated_sales_form');
    Route::get('/reports/estimated_sales/{market_day}', 'ReportController@estimatedSales')->name('reports.estimated_sales');
    Route::get('/reports/distribute_scrip_form', 'ReportController@distributeScripForm')->name('reports.distribute_scrip_form');
    Route::get('/reports/distribute_scrip/{market_day}', 'ReportController@distributeScrip')->name('reports.distribute_scrip');
    Route::get('/reports/collect_scrip_form', 'ReportController@collectScripForm')->name('reports.collect_scrip_form');
    Route::get('/reports/collect_scrip/{market_day}', 'ReportController@collectScrip')->name('reports.collect_scrip');

    Route::get('/reports/tableau_export_form', 'ReportController@tableauExportForm')->name('reports.tableau_export_form');
    Route::get('/reports/tableau_export/{market_day}', 'ReportController@tableauExport')->name('reports.tableau_export');



	// ADMIN tools

	Route::get('/admin', function () {
        return view('admin.index');
    })->name('admin');


	Route::group(['prefix' => 'admin'], function () {


	    // Routes below are long form of:
	    // Route::resource('markets', 'MarketController');
	    Route::get('/markets', 'MarketController@index')->name('markets.index');
	    Route::get('/markets/create', 'MarketController@create')->name('markets.create');
	    Route::post('/markets', 'MarketController@store')->name('markets.store');
	    Route::get('/markets/{market}', 'MarketController@show')->name('markets.show');
	    Route::get('/markets/{market}/edit', 'MarketController@edit')->name('markets.edit');
	    Route::put('/markets/{market}', 'MarketController@update')->name('markets.update');
	    Route::patch('/markets/{market}', 'MarketController@update')->name('markets.update');
	    Route::delete('/markets/{market}', 'MarketController@destroy')->name('markets.destroy');

	    // Routes below are long form of:
	    // Route::resource('vendors', 'VendorController');
	    Route::get('/vendors', 'VendorController@index')->name('vendors.index');
	    Route::get('/vendors/create', 'VendorController@create')->name('vendors.create');
	    Route::post('/vendors', 'VendorController@store')->name('vendors.store');
	    Route::get('/vendors/{vendor}', 'VendorController@show')->name('vendors.show');
	    Route::get('/vendors/{vendor}/edit', 'VendorController@edit')->name('vendors.edit');
	    Route::put('/vendors/{vendor}', 'VendorController@update')->name('vendors.update');
	    Route::patch('/vendors/{vendor}', 'VendorController@update')->name('vendors.update');
	    Route::delete('/vendors/{vendor}', 'VendorController@destroy')->name('vendors.destroy');
        Route::get('/vendors/{id}/restore', 'VendorController@restore')->name('vendors.restore');

	   // Routes below are long form of:
	    // Route::resource('vendortypes', 'VendorTypeController');
	    Route::get('/vendortypes', 'VendorTypeController@index')->name('vendortypes.index');
	    Route::get('/vendortypes/create', 'VendorTypeController@create')->name('vendortypes.create');
	    Route::post('/vendortypes', 'VendorTypeController@store')->name('vendortypes.store');
	    Route::get('/vendortypes/{vendortype}', 'VendorTypeController@show')->name('vendortypes.show');
	    Route::get('/vendortypes/{vendortype}/edit', 'VendorTypeController@edit')->name('vendortypes.edit');
	    Route::put('/vendortypes/{vendortype}', 'VendorTypeController@update')->name('vendortypes.update');
	    Route::patch('/vendortypes/{vendortype}', 'VendorTypeController@update')->name('vendortypes.update');
	    Route::delete('/vendortypes/{vendortype}', 'VendorTypeController@destroy')->name('vendortypes.destroy');

	    // Routes below are long form of:
	    // Route::resource('scrips', 'ScripController');
	    Route::get('/scrips', 'ScripController@index')->name('scrips.index');
	    Route::get('/scrips/create', 'ScripController@create')->name('scrips.create');
	    Route::post('/scrips', 'ScripController@store')->name('scrips.store');
	    Route::get('/scrips/{scrip}', 'ScripController@show')->name('scrips.show');
	    Route::get('/scrips/{scrip}/edit', 'ScripController@edit')->name('scrips.edit');
	    Route::put('/scrips/{scrip}', 'ScripController@update')->name('scrips.update');
	    Route::patch('/scrips/{scrip}', 'ScripController@update')->name('scrips.update');
	    Route::delete('/scrips/{scrip}', 'ScripController@destroy')->name('scrips.destroy');
        Route::get('/scrips/{id}/restore', 'ScripController@restore')->name('scrips.restore');


        // Routes below are long form of:
	    // Route::resource('market-days', 'MarketDayController');
	    Route::get('/market_days', 'MarketDayController@index')->name('market_days.index');
	    Route::get('/market_days/create', 'MarketDayController@create')->name('market_days.create');
	    Route::post('/market_days', 'MarketDayController@store')->name('market_days.store');
	    Route::get('/market_days/{market_day}', 'MarketDayController@show')->name('market_days.show');
	    Route::get('/market_days/{market_day}/edit', 'MarketDayController@edit')->name('market_days.edit');
	    Route::put('/market_days/{market_day}', 'MarketDayController@update')->name('market_days.update');
	    Route::patch('/market_days/{market_day}', 'MarketDayController@update')->name('market_days.update');
	    Route::delete('/market_days/{market_day}', 'MarketDayController@destroy')->name('market_days.destroy');
	    Route::get('/market_days/{market_day}/batch_upload', 'MarketDayController@showBatchUpload')->name('market_days.batch_upload');
	    Route::post('/market_days/{market_day}/batch_upload', 'MarketDayController@doBatchUpload')->name('market_days.do_batch_upload');
	}); // prefix
});

app/MarketDay.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class MarketDay extends Model
{
    use SoftDeletes;
    
    protected $table = "market_days";

    protected $dates = ['created_at', 'updated_at', 'date'];

    public function market() {
        return $this->belongsTo('App\Market');
    }

    public function vendors() {
        return $this->belongsToMany('App\Vendor', 'vendor_to_market_days', 'market_day_id', 'vendor_id')
            ->withPivot('id', 'booth_fee', 'booth_fee_note', 'booths_paid_for', 'estimated_sales', 'estimated_sales_note', 'collected_scrip_note', 'location_order', 'attended_market', 'collected_estimated_sales')
            ->withTrashed()
            ->using('App\MarketDayVendor')
            ->withTimestamps();
    }

    public function scrip_sales() {
        return $this->hasMany('App\ScripSale');
    }

    public function brought_scrips() {
        return $this->belongsToMany('App\Scrip', 'market_day_brought_scrips', 'market_day_id', 'scrip_id')
            ->withPivot('id', 'pieces')
            ->withTimestamps()
            ->withTrashed();
    }

    public function getScripSoldCountById($scrip_id) {
        $count = 0;

        // Sale:
        $this->scrip_sales->each(function($scrip_sale) use (&$count, $scrip_id){
            $count += $scrip_sale->scrips()->where('scrip_id', $scrip_id)->sum('amount');
        });

        return $count;
    }

    public function getCollectedBoothFeeCountAttribute()
    {
        return $this->vendors()->wherePivot('collected_booth_fee', true)->count();
    }

    public function getTotalBoothFeesAttribute()
    {
        return $this->vendors()->wherePivot('collected_booth_fee', true)->sum('booth_fee');
    }

    public function getVendorsThatCanCollectScripCountAttribute()
    {
        return $this->vendors()->wherePivot('attended_market',true)->whereHas('scrips', function ($query) {
            $query->where('accepted', true);
        })->count();
    }

    public function getVendorsThatCollectedScripCountAttribute()
    {
        return $this->vendors()->wherePivot('collected_scrip', true)->count();
    }

    public function getCollectedScripTotalAttribute()
    {
        $total = 0;

        $this->vendors->each(function ($vendor, $key) use (&$total) {
            $vendor->market_days()
                ->where('market_days.id', $this->id)
                ->first()
                ->pivot
                ->scrips
                ->each(function($scrip) use (&$total) {
                    $total += ( $scrip->pivot->pieces_collected * (int)$scrip->denomination );
                });
        });

        return $total;
    }

    public function getCollectedScripCountAttribute()
    {
        $count = 0;

        $this->vendors->each(function ($vendor, $key) use (&$count) {
            $count += $vendor->market_days()
                ->where('market_days.id', $this->id)
                ->first()
                ->pivot
                ->scrips()
                ->sum('pieces_collected');
        });

        return $count;
    }

    public function getScripSoldCountAttribute()
    {
        $count = 0;

        // Sale:
        $this->scrip_sales->each(function($scrip_sale) use (&$count){
            // Line Item:
            $scrip_sale->scrips->each(function($scrip) use (&$count){
                // Quantity:
                $count += $scrip->pivot->amount;
            });
        });

        return $count;
    }

    public function getScripSoldTotalAttribute()
    {
        $total = 0;

        // Sale:
        $this->scrip_sales->each(function($scrip_sale) use (&$total){
            // Line Item:
            $scrip_sale->scrips->each(function($scrip) use (&$total){
                // $$ total
                $total += ($scrip->pivot->amount * (int)$scrip->denomination);
            });
        });

        return $total;
    }

    public function getEstimatedSalesCountAttribute()
    {
		return $this->vendors()->wherePivot('collected_estimated_sales', true)->count();

    }

    public function getEstimatedSalesTotalAttribute()
    {
        return $this->vendors()->wherePivot('collected_estimated_sales', true)->sum('estimated_sales');
    }

    /**
     * Return all vendors for this market day.
     *
     * @return string
     */
    public function getVendorsForMultiSelect()
    {
        $vendors = [];

        foreach ($this->vendors()->wherePivot('attended_market',true)->orderBy('location_order')->get() as $vendor) {
            $vendors[] = [
                'value' => $vendor->id,
                'text' => $vendor->name
            ];
        }

        return $vendors;
    }

    //Eric's attempt to get the scrips colelcted per vendor
    public function getVendorsScripCollectedInfoAttribute()
    {

		// array to hold scrip types and pieces_collected
        $collected_scrip = [];


		// loop over each vendor and 'return' $collected_scrip after loop
        $this->vendors->each(function ($vendor, $key) use (&$collected_scrip) {

			$collected_scrip[$vendor->name] = [];
            $collected_scrip[$vendor->name]['id'] = $vendor->id;
            $collected_scrip[$vendor->name]['vendor_name'] = $vendor->name;
			$collected_scrip[$vendor->name]['collected_scrip_note'] = $vendor->pivot->collected_scrip_note;
            $collected_scrip[$vendor->name]['scrip_collected'] = [];

            $vendor->market_days()
                ->where('market_days.id', $this->id)
                ->first()
                // We're accessing the Market Day off the vendor so we have access to 'pivot'
                // the pivot is represented by MarketDayVendor
                ->pivot
                ->scrips // relationship of MarketDayVendor
                ->each(function ($scrip) use (&$collected_scrip, $vendor) {
                    $collected_scrip[$vendor->name]['scrip_collected'][$scrip->name] = ['pieces'=>$scrip->pivot->pieces_collected, 'denomination'=>$scrip->denomination];
					$collected_scrip[$vendor->name]['scrip_id'] = $scrip->pivot->scrip_id;

                });
		});

        return $collected_scrip;
    }


}

resources/views/tools/dashboard.blade.php
@extends('layouts.app')


@section('content')

    <div class="content clearfix">
		<div class="row">

			<div class="col-sm-5">
		        <h2 class="title">Current Market Status</h2>
			</div>
			<div class="col-sm-6">
				&nbsp;
			</div>
		</div>
        <hr>

		@hasrole(['superadmin','double_dollar_coordinator','double_dollar_associate'])
			@if ($market_day->scrip_comments != '')
				<div class="row">
					<div class="col-sm-12">
			            <div class="col-sm-11 bg-info"  style="padding:15px;">
							<small><u>DDIP Comments:</u></small><br>
			                {{ $market_day->scrip_comments }}
			            </div>
					</div>
		        </div>
				<hr>
			@endif
		@endhasrole

		@hasrole(['superadmin','market_coordinator','market_crew'])
			@if ($market_day->market_comments != '')
				<div class="row">
					<div class="col-sm-12">
			            <div class="col-sm-11 bg-info"  style="padding:15px;">
				            <small><u>Market Comments:</u></small><br>
			                {{ $market_day->market_comments }}
			            </div>
					</div>
		        </div>
				<hr>
			@endif

			<div class="row">
	            <div class="col-sm-9 col-sm-offset-1">
				<div class="table-responsive">
                <table class="table table-hover table-striped">
                    <thead>
                        <tr  class='success'>
							<th>&nbsp;</th>
							<th>&nbsp;</th>
							<th>Completed</th>
							<th>Vendors</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr >
							<td>&nbsp;</td>
							<td>
								<a href="{{ route('tools.show_booth_fees', ['market_day' => $market_day->id]) }}">
									<i class="icon_div ti-booth_fees"></i>Booth Fees
								</a>
							</td>
							<td>
								<span class="@if( $vendor_attended_total - $market_day->collected_booth_fee_count  > 0) text-warning @endif">
			                        {{ $market_day->collected_booth_fee_count }}
			                    </span>
								@hasrole(['superadmin','market_coordinator'])
				                    @ ${{ $market_day->total_booth_fees }}
				                @endhasrole
							</td>
							<td>{{ $vendor_expected_up_total }} expected</td>
                        </tr>
                        <tr >
							<td>&nbsp;</td>
							<td>
								<a href="{{ route('tools.show_collect_scrips', ['market_day' => $market_day->id]) }}">
									<i class="icon_div ti-scrips"></i>Scrip Collected
								</a>
							</td>
							<td>
								<span class="@if($market_day->vendors_that_can_collect_scrip_count - $market_day->vendors_that_collected_scrip_count > 0) text-warning @endif">
			                        {{ $market_day->vendors_that_collected_scrip_count }}
			                    </span>
								@hasrole(['superadmin','market_coordinator'])
				                    @ ${{ $market_day->collected_scrip_total }}
				                @endhasrole
							</td>
							<td>{{ $vendor_attended_total }} present</td>
                        </tr>
							<td>&nbsp;</td>
							<td>
								<a href="{{ route('tools.show_estimated_sales', ['market_day' => $market_day->id]) }}">
									<i class="icon_div ti-estimated_sales"></i>Estimated Sales
								</a>
							</td>
							<td>
								<span class="@if($vendor_attended_total - $market_day->estimated_sales_count > 0) text-warning @endif">
			                        {{ $market_day->estimated_sales_count }}
			                    </span>
								@hasrole(['superadmin','market_coordinator'])
				                    @ ${{ $market_day->estimated_sales_total }}
								@endhasrole
							</td>
							<td>{{ $vendor_attended_total }} present</td>
                    </tbody>
                </table>
				</div>
	            </div>
			</div>

		@endhasrole

		{{-- admin see both, so give a line break --}}
		@hasrole('superadmin')
			<br clear="all">
		@endhasrole


		@hasrole(['superadmin','double_dollar_coordinator','double_dollar_associate'])

	        <div class="row">
	            <div class="col-sm-9 col-sm-offset-1">
		            <div class="table-responsive">
		                <table class="table table-hover table-striped">
		                    <thead>
		                        <tr  class='success'>
		                            <th>Scrip Name</th>
		                            <th>Brought</th>
		                            <th>Distributed</th>
		                            <th>Remaining</th>
		                        </tr>
		                    </thead>
		                    <tbody>
		                        @foreach ($scrips as $scrip)
		                            <tr>
		                                <td>{{ $scrip->name }}</td>
		                                @if ($market_day->brought_scrips()->where('scrip_id', $scrip->id)->count())
		                                    <td>{{ $brought_pieces = $market_day->brought_scrips()->where('scrip_id', $scrip->id)->first()->pivot->pieces }}</td>
		                                @else
		                                    <td>{{ $brought_pieces = 0 }}</td>
		                                @endif
		                                <td>{{ $distributed = $market_day->getScripSoldCountById($scrip->id) }}</td>
		                                <td>
			                                {{-- show alert if below 0 --}}
			                                <span class="@if ($brought_pieces - $distributed < 0)text-warning @endif">
			                                {{ $brought_pieces - $distributed }}
			                                </span>
			                            </td>

		                            </tr>
		                        @endforeach
		                    </tbody>
		                </table>
		            </div>
	            </div>
	        </div>
        @endhasrole

    </div>


@endsection

resources/views/tools/manage.blade.php
@extends('layouts.app')


@section('content')

    <div class="content clearfix">
		<div class="row">

			<div class="col-sm-5">
		        <h2 class="title">Current Market Status</h2>
			</div>
			<div class="col-sm-6">
				&nbsp;
			</div>
		</div>
        <hr>


		@hasrole(['superadmin','double_dollar_coordinator','double_dollar_associate'])
			@if ($market_day->scrip_comments != '')
				<div class="row">
					<div class="col-sm-12">
			            <div class="col-sm-11 bg-info"  style="padding:15px;">
							<small><u>DDIP Comments:</u></small><br>
			                {{ $market_day->scrip_comments }}
			            </div>
					</div>
		        </div>
				<hr>
			@endif
		@endhasrole

		@hasrole(['superadmin','market_coordinator','market_crew'])
			@if ($market_day->market_comments != '')
				<div class="row">
					<div class="col-sm-12">
			            <div class="col-sm-11 bg-info"  style="padding:15px;">
				            <small><u>Market Comments:</u></small><br>
			                {{ $market_day->market_comments }}
			            </div>
					</div>
		        </div>
				<hr>
			@endif
{{--	        <div class="row">
	            <div class="col-sm-3">
	                <h4 class="title">Scrip Collected</h4>
	            </div>
	            <div class="col-sm-3">
	                <h4 class="title bold">{{ $market_day->collected_scrip_count }} @ ${{ $market_day->collected_scrip_total }}</h4>
	            </div>
	        </div>
--}}

			<div class="row">
	            <div class="col-sm-3">
	                &nbsp;
	            </div>
	            <div class="col-sm-3">
	                <h4 class="title">Completed</h4>
	            </div>
	            <div class="col-sm-3">
	                <h4 class="title">Total Vendors</h4>
	            </div>

	        </div>

			 <div class="row">
	            <div class="col-sm-3">
	                <h4 class="title"><i class="icon_div ti-booth_fees"></i>Booth Fees</h4>
	            </div>
	            <div class="col-sm-3">
	                <h4 class="title bold">
	                    <span class="@if($market_day->vendors->count() - $market_day->collected_booth_fee_count > 0) text-warning @endif">
	                        {{ $market_day->collected_booth_fee_count }}
	                    </span>
						@hasrole(['superadmin','market_coordinator'])
		                     @ ${{ $market_day->total_booth_fees }}
						@endhasrole
	                </h4>
	            </div>
	            <div class="col-sm-3">
	                <h4 class="title bold">{{ $market_day->vendors->count() }}</h4>
	            </div>
	        </div>

	        <div class="row">
	            <div class="col-sm-3">
	                <h4 class="title"><i class="icon_div ti-scrips"></i>Scrip Collected</h4>
	            </div>
	            <div class="col-sm-3">
	                <h4 class="title bold">
	                    <span class="@if($market_day->vendors_that_can_collect_scrip_count - $market_day->vendors_that_collected_scrip_count > 0) text-warning @endif">
	                        {{ $market_day->vendors_that_collected_scrip_count }}
	                    </span>
						@hasrole(['superadmin','market_coordinator'])
		                    @ ${{ $market_day->collected_scrip_total }}
		                @endhasrole
	                </h4>
	            </div>
	            <div class="col-sm-3">
	                <h4 class="title bold">{{ $market_day->vendors_that_can_collect_scrip_count }}</h4>
	            </div>

	        </div>
			<div class="row">
	            <div class="col-sm-3">
	                <h4 class="title"><i class="icon_div ti-estimated_sales"></i>Estimated Sales</h4>
	            </div>
	            <div class="col-sm-3">
	                <h4 class="title bold">
	                    <span class="text-warning">
	                        {{ $market_day->estimated_sales_count }}
	                    </span>
						@hasrole(['superadmin','market_coordinator'])
		                    @ ${{ $market_day->estimated_sales_total }}
						@endhasrole
	                </h4>
	            </div>
	            <div class="col-sm-3">
	                <h4 class="title bold">{{ $market_day->vendors->count() }}</h4>
	            </div>

	        </div>
		@endhasrole

		@hasrole(['superadmin','double_dollar_coordinator','double_dollar_associate'])

	        <div class="row">
	            <div class="col-sm-9 col-sm-offset-1">
		            <div class="table-responsive">
		                <table class="table table-hover table-striped">
		                    <thead>
		                        <tr  class='success'>
		                            <th>Scrip Name</th>
		                            <th>Brought</th>
		                            <th>Distributed</th>
		                            <th>Remaining</th>
		                        </tr>
		                    </thead>
		                    <tbody>
		                        @foreach ($scrips as $scrip)
		                            <tr>
		                                <td>{{ $scrip->name }}</td>
		                                @if ($market_day->brought_scrips()->where('scrip_id', $scrip->id)->count())
		                                    <td>{{ $brought_pieces = $market_day->brought_scrips()->where('scrip_id', $scrip->id)->first()->pivot->pieces }}</td>
		                                @else
		                                    <td>{{ $brought_pieces = 0 }}</td>
		                                @endif
		                                <td>{{ $distributed = $market_day->getScripSoldCountById($scrip->id) }}</td>
		                                <td>
			                                {{-- show alert if below 0 --}}
			                                <span class="@if ($brought_pieces - $distributed < 0)text-warning @endif">
			                                {{ $brought_pieces - $distributed }}
			                                </span>
			                            </td>

		                            </tr>
		                        @endforeach
		                    </tbody>
		                </table>
		            </div>
	            </div>
	        </div>
        @endhasrole

    </div>


@endsection

resources/views/tools/show_collected_scrips.blade.php
@extends('layouts.app')

@section('content')
<div class="content clearfix">
	<div class="row">

		<div class="col-sm-5">
	        <h2 class="title"><i class="icon_div ti-scrips"></i>Collect Scrip</h2>
		</div>
		<div class="col-sm-6">
			&nbsp;
		</div>
	</div>
    <hr>
</div>




@include('vendor_search', ['tool' => 'show_collect_scrips_for_vendor'])

<div class="row">

	<div class="col-sm-10">

{{--		<a class="btn btn-primary" href="{{ route('tools.show_collect_scrips_for_vendor', ['market_day' => $market_day->id, 'vendor' => $vendor->id]) }}">First Vendor</a>
		<br><br>
--}}
		{{-- make table responsive --}}
		<div class="table-responsive" style+"width">

			<table class="table table-hover table-striped">
			    <thead>
			        <tr class='success'>
			            <th>&nbsp;</th>
			            <th>Vendor</th>
			            <th>Scrip</th>
			            <th>Notes</th>
			    	</tr>
			    </thead>
			    <tbody>
{{-- 				@foreach ($market_day->vendors_scrip_collected_info as $vendor_name => $scrips_collected) --}}
					@foreach ($market_day->vendors()->orderBy("name")->get() as $vendor)

					@php ($scrips_collected=$market_day->vendors_scrip_collected_info[$vendor->name])
			        <tr>
				        <td>
					        @if ($vendor->pivot->attended_market)
								<a class='btn btn-info btn-lg' href="{{ route('tools.show_collect_scrips_for_vendor', ['market_day' => $market_day->id, 'vendor' => $scrips_collected['id']]) }}">
								Enter
								</a>
							@else
								<small class='text-warning'>Not at market</small>
							@endif
				        </td>
						<td>
							{{$vendor->name}}
						</td>
						<td>
							<ul>
							@if (! $vendor->pivot->attended_market)
								--
							@else
								@foreach ($scrips_collected['scrip_collected'] as $scrip_name => $scrip_count)
									<li>{{ $scrip_name }} | {{ $scrip_count['pieces'] }} pieces</li>
								@endforeach
							@endif
							</ul>
						</td>
						<td>
							{{$vendor->pivot->collected_scrip_note}}
						</td>

			        </tr>
					@endforeach
			    </tbody>
			</table>
		</div>

	</div>
</div>


@endsection